CREATE TABLE donnees_geo_climatiques (
    code_insee_com TEXT PRIMARY KEY,
    nom_com TEXT,
    reg_code INT,
    reg_nom INT,
    dep_code INT,
    dep_nom, 
    population, 
    superficie_km2, 
    densite, 
    latitude, 
    longitude, 
    densite_cat, 
    alti_med, 
    RR_med, 
    NBJRR1_med, 
    NBJRR5_med, 
    NBJRR10_med, 
    Tmin_med, 
    Tmax_med, 
    Tens_vap_med, 
    Force_vent_med, 
    Insolation_med, 
    Rayonnement_med
)
